---
title: "Hennepin County tidycensus map"
format: html
editor: visual
---

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(sf)
library(tidyverse)
library(ggmap)
library(tmap)
library(tidycensus)
library(leaflet)
library(osmdata)
library(tigris)
library(janitor)
library(viridis)
library(ggthemes)
library(stringr)
library(plotly)
library(ggplot2)
```

### leaflet of the entire state of MN

------------------------------------------------------------------------

```{r data_read, include = FALSE}
### 1.3 Please create 1 ggplotly of Hennepin County using sf, ggmap, tidycensus, ggplot, and plotly
## Request the ACS estimates for * Count of managment, art and social service occupations* in Hennepin County, MN
#Get the bounding box and county outline
mn.box           <- osmdata::getbb("minnesota")
hennepin.box     <- osmdata::getbb("hennepin")
hennepin.outline <- osmdata::getbb("hennepin", format_out = "polygon")[[1]] %>%
  as_tibble() %>%
  rename(longitude = V1, latitude = V2)


#Get map from ggmap
#Get the base map (foundational layer)
mn_base.map <- get_map(
                location = hennepin.box,
                source   = "stamen",
                maptype  = "terrain",
                crop = TRUE
               )

#Create the base map
hennepin_base.gg <- ggmap(mn_base.map) +
  geom_polygon(data = hennepin.outline, aes(x = longitude, y = latitude), colour = "black", size = 1.6, alpha = 0.1) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )

options(tigris_use_cache = TRUE)

Sys.getenv("CENSUS_API_KEY")
mn_op.df <- get_acs(
  geography = "tract",
  variables = "C24060_002E", #Code for median rent
  state     = "MN",
  county    = "Hennepin",
  year      = 2020,
  geometry  = TRUE
)

#Add a text label to mn_op.df
mn_op_plotly.df <- mn_op.df %>%
  mutate(
    tract      = str_split(NAME, ",") %>%
                 map_chr(1) %>%
                 str_remove("Census Tract "),
    text_label = str_c(
                  "Count: ",
                  tract,
                  "\nOccupation: managment, art and social service"
                  
                 )
  )
#Generate the ggplot
occupation.gg <- ggplot() + 
  geom_sf(data = mn_op_plotly.df, 
          aes(fill = estimate, text = text_label),
          colour = "black", size = 0.1) + 
  labs(title = "Hennepin County, MN 2020 ACS Occupation Count") + 
  scale_fill_viridis_c("Occupation count",labels = scales::number) +
  theme_map() +
  theme(
    plot.title   = element_text(size  = 16,
                                hjust = 0.5),
    legend.text  = element_text(size = 16),
    legend.title = element_text(size = 16),
    legend.position = "right"
  )
#Display
ggplotly(occupation.gg,
         tooltip = "text",
         height  = 600,
         width   = 800) %>%
    style(hoveron = "fills")
```
